-- Script de suppression des données des tables

DELETE FROM CLIENT;
DELETE FROM CONTRAT;
DELETE FROM VEHICULE;
DELETE FROM IMPLICATION;
DELETE FROM ACCIDENT;

ALTER TABLE CLIENT
DROP PRIMARY KEY;

ALTER TABLE CONTRAT
DROP PRIMARY KEY;

ALTER TABLE VEHICULE
DROP PRIMARY KEY;

ALTER TABLE IMPLICATION
DROP PRIMARY KEY;

ALTER TABLE ACCIDENT
DROP PRIMARY KEY;

ALTER TABLE CONTRAT    /*Suppression de la contrainte de la foreign key "CONTRAT"*/
DROP FOREIGN KEY FK_NUMCLIENT;


/*Suppression des index*/
ALTER TABLE CLIENT
DROP INDEX I_CLIENT;

ALTER TABLE CONTRAT
DROP INDEX I_CONTRAT;

ALTER TABLE VEHICULE
DROP INDEX I_VEHICULE;

ALTER TABLE IMPLICATION
DROP INDEX I_IMPLICATION;

ALTER TABLE ACCIDENT
DROP INDEX I_ACCIDENT;

DROP TABLE CONTRAT;
DROP TABLE CLIENT;
DROP TABLE ACCIDENT;
DROP TABLE IMPLICATION;
DROP TABLE VEHICULE;


